[change] tank skeleton to use sprite
kiraki-dev/kiraki-games pull request #16
Opened 2020-12-07 10:59 UTC by MyasnikKhachkalyan

2020-12-07 19:41 UTC, hakobpogh requested changes
- [ ] And where are the EnemyTank changes?

2020-12-07 19:41 UTC, hakobpogh commented on src/components/TankSkeletons/AllyTankSkeleton.tsx
> +  return <div style={inlineStyles} className={[styles.TankSkeleton, styles.AllyTankSkeleton].join(' ')} />;
- [ ] I suggest moving `[styles.TankSkeleton, styles.AllyTankSkeleton].join(' ')` to a separate variable for clearance.

2020-12-07 19:41 UTC, hakobpogh commented on src/components/TankSkeletons/TankSkeleton.module.scss
> +  var(--tank-skeleton-bg-x) var(--tank-skeleton-bg-y);
- [ ] Add `/* background-position */` comment here to add a bit of clarity here.

2020-12-07 19:42 UTC, hakobpogh approved these changes

2020-12-10 12:23 UTC, hospogh approved these changes

2020-12-10 12:23 UTC, merged